apiVersion: v2
name: sd-trade-finance
description: "BIAN Service Domain: Trade Finance (Fulfill pattern, Operations and Execution)"
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - bian
  - fulfill
annotations:
  bian/business-area: "Operations and Execution"
  bian/business-domain: "Trade Banking"
  bian/asset-type: "Trade Finance Facility"
  bian/control-record: "Trade Finance Facility Fulfillment Arrangement"
